services:
    chat_web:
        container_name: chat_web
        image: nginx:alpine
        ports:
            - "8030:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - chat_app
        networks:
            - chat_network
    chat_app:
        container_name: chat_app
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        depends_on:
            - chat_db
        volumes:
            - ./:/var/www
        networks:
            - chat_network
        ports:
            - "9070:9000"
    chat_db:
        image: mysql
        container_name: chat_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - chat_database:/var/lib/mysql
        networks:
            - chat_network
        ports:
            -   "3208:3206"
    chat_node:
        container_name: chat_node
        image: node:alpine
        volumes:
            - ./:/var/www
        command: sh -c "npm install && npm run build"
        depends_on:
            -   chat_app
        ports:
            - "8020:8000"
networks:
    chat_network:
        driver: bridge
volumes:
    chat_database:
